In [11]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/book-recommendation-dataset/Ratings.csv
/kaggle/input/book-recommendation-dataset/Users.csv
/kaggle/input/book-recommendation-dataset/classicRec.png
/kaggle/input/book-recommendation-dataset/Books.csv
/kaggle/input/book-recommendation-dataset/DeepRec.png
/kaggle/input/book-recommendation-dataset/recsys_taxonomy2.png

In [12]:
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [13]:
ratings = pd.read_csv("/kaggle/input/book-recommendation-dataset/Ratings.csv")
books = pd.read_csv("/kaggle/input/book-recommendation-dataset/Books.csv")
users = pd.read_csv("/kaggle/input/book-recommendation-dataset/Users.csv")

In [14]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1149780 non-null  int64
 1   ISBN         1149780 non-null  object
 2   Book-Rating  1149780 non-null  int64
dtypes: int64(2), object(1)
memory usage: 26.3+ MB

In [15]:
ratings.shape

(1149780, 3)

In [16]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [17]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271358 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-S          271360 non-null  object
 6   Image-URL-M          271360 non-null  object
 7   Image-URL-L          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

In [18]:
books.shape

(271360, 8)

In [19]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [20]:
books['ISBN'].nunique()

271360

In [21]:
books['Book-Title'].nunique()

242135

In [22]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278858 entries, 0 to 278857
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   User-ID   278858 non-null  int64
 1   Location  278858 non-null  object
 2   Age       168096 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.4+ MB

In [23]:
users.shape

(278858, 3)

In [24]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [25]:
books.duplicated().sum()

0

In [26]:
users.duplicated().sum()

0

In [27]:
ratings.duplicated().sum()

0

In [28]:
books.isna().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [29]:
users.isna().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [30]:
ratings.isna().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [31]:
count_name = pd.DataFrame(books['Book-Title'].value_counts())

In [32]:
count_name.reset_index(inplace=True)

In [33]:
count_name.rename(columns={'index':'Book-Title','Book-Title':'Count'})

                                                    Count  count
0                                          Selected Poems     27
1                                            Little Women     24
2                                       Wuthering Heights     21
3                                       The Secret Garden     20
4                                                 Dracula     20
...                                                   ...    ...
242130                         What Every Kid Should Know      1
242131          The Seventh Enemy (A Brady Coyne Mystery)      1
242132                                   A Brace of Skeet      1
242133  The Yellow Admiral (O'Brian, Patrick, Aubrey/M...      1
242134  A Guided Tour of Rene Descartes' Meditations o...      1

[242135 rows x 2 columns]

In [34]:
count_name.sample(3)

                                               Book-Title  count
149612  Unexpected Babies (The Talbot Twins) (Harlequi...      1
72903                                     Cheyenne Autumn      1
92312                                        To My Sister      1

This will creates a DataFrame showing the number of ratings each user has given.

In [35]:
User_Rating_Count = pd.DataFrame(ratings['User-ID'].value_counts()).reset_index()
User_Rating_Count.columns = ['User-ID', 'count']

In [36]:
User_Rating_Count.sample()

       User-ID  count
39401   252917      2

This will merge the Ratings table with Books On ISBN

In [37]:
df_merge = ratings.merge(books, on='ISBN')

In [38]:
df_merge.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...

In [39]:
df_merge[df_merge["Book-Rating"]== df_merge["Book-Rating"].max()].head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
45,276772,3499230933,10,Adressat unbekannt.,Kathrine Kressmann Taylor,2002,Rowohlt Tb.,http://images.amazon.com/images/P/3499230933.0...,http://images.amazon.com/images/P/3499230933.0...,http://images.amazon.com/images/P/3499230933.0...
46,276772,3596151465,10,Henry der Held.,Roddy Doyle,2001,"Fischer (Tb.), Frankfurt",http://images.amazon.com/images/P/3596151465.0...,http://images.amazon.com/images/P/3596151465.0...,http://images.amazon.com/images/P/3596151465.0...
61,276788,055310666X,10,False Memory,Dean R. Koontz,1999,Bantam Books,http://images.amazon.com/images/P/055310666X.0...,http://images.amazon.com/images/P/055310666X.0...,http://images.amazon.com/images/P/055310666X.0...
83,276808,0395547032,10,Richard Brautigan : A Confederate General from...,Richard Brautigan,1991,Mariner Books,http://images.amazon.com/images/P/0395547032.0...,http://images.amazon.com/images/P/0395547032.0...,http://images.amazon.com/images/P/0395547032.0...
84,276811,0440414121,10,The Watsons Go to Birmingham - 1963 (Yearling ...,CHRISTOPHER PAUL CURTIS,1997,Yearling,http://images.amazon.com/images/P/0440414121.0...,http://images.amazon.com/images/P/0440414121.0...,http://images.amazon.com/images/P/0440414121.0...

This will calculates how many times each book has been rated

In [48]:
num_rating_count = df_merge.groupby(['Book-Title']).count()["Book-Rating"].reset_index()
num_rating_count.rename(columns = {
    "Book-Rating": "num_rating"
},inplace=True)

This will calculates the average rating for each book title.

In [49]:
This line calculates the average rating for each book title.
avg_ratings.rename(columns={'Book-Rating': 'avg_rating'}, inplace=True)

avg_ratings

                                               Book-Title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

This will merge the Rating counts with the avg of ratings tables

In [50]:
pop_df = num_rating_count.merge(avg_ratings, on='Book-Title')

In [51]:
pop_df.sample(2)

,Book-Title,num_rating,avg_rating
14332,Angel's Bidding,2,3.5
174668,The Absence of Peace : Understanding the Israe...,1,2.0

This line filters books with at least 200 ratings and sorts them by average rating in descending order.

In [59]:
top_df = pop_df[pop_df['num_rating'] >= 200].sort_values("avg_rating",ascending=False)
top_df.sample(3)

,Book-Title,num_rating,avg_rating
27600,Breathing Lessons,239,2.117155
81845,Heaven and Earth (Three Sisters Island Trilogy),210,2.866667
134035,One Door Away from Heaven,298,3.389262

This code will sorts the filtered top books by the number of ratings in descending order to find the most rated ones.

In [60]:
best_rating = top_df.sort_values("num_rating",ascending=False)
best_rating.head()

                        Book-Title  num_rating  avg_rating
234951                 Wild Animus        2502    1.019584
196326   The Lovely Bones: A Novel        1295    4.468726
183573           The Da Vinci Code         898    4.642539
5303               A Painted House         838    3.231504
199237  The Nanny Diaries: A Novel         828    3.530193

In [61]:
top_df.describe()

        num_rating  avg_rating
count   297.000000  297.000000
mean    334.158249    3.348791
std     192.388012    0.691813
min     200.000000    1.019584
25%     228.000000    2.900602
50%     274.000000    3.290795
75%     378.000000    3.704918
max    2502.000000    5.852804

This line merges book details into the top-rated books DataFrame, removes duplicates by book title, and selects relevant columns for display.

In [63]:
top_df = top_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','num_rating','avg_rating']]

In [64]:
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_colwidth', 1000)

This line checks which users have rated more than 200 books

In [65]:
x = df_merge.groupby('User-ID').count()['Book-Rating'] > 200
x

User-ID
2         False
8         False
9         False
10        False
12        False
          ...
278846    False
278849    False
278851    False
278852    False
278854    False
Name: Book-Rating, Length: 92106, dtype: bool

Extracts the User-IDs of users who have rated more than 200 books.

In [66]:
wellread_users = x[x].index

This line filters the ratings DataFrame to include only those entries made by well-read users (who rated more than 200 books).

In [69]:
filtered_rating = df_merge[df_merge['User-ID'].isin(wellread_users)]
filtered_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Tales for Our Life and Times,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/002542730X.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/002542730X.01.LZZZZZZZ.jpg
1151,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/0026217457.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/0026217457.01.LZZZZZZZ.jpg
1152,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/003008685X.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/003008685X.01.LZZZZZZZ.jpg
1153,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/0030615321.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/0030615321.01.LZZZZZZZ.jpg
1154,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/0060002050.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/0060002050.01.LZZZZZZZ.jpg
...,...,...,...,...,...,...,...,...,...,...
1029357,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventures of a Mountain Man Wannabe (Capital Discoveries Book),Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/1931868123.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/1931868123.01.LZZZZZZZ.jpg
1029358,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/3411086211.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/3411086211.01.LZZZZZZZ.jpg
1029359,275970,3829021860,0,The Penis Book,Joseph Cohen,1999,Konemann,http://images.amazon.com/images/P/3829021860.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/3829021860.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/3829021860.01.LZZZZZZZ.jpg
1029360,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995,Kodansha International (JPN),http://images.amazon.com/images/P/4770019572.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/4770019572.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/4770019572.01.LZZZZZZZ.jpg
1029361,275970,9626340762,8,Northanger Abbey (Classic Literature with Classical Music),Jane Austen,1996,Naxos Audiobooks Ltd.,http://images.amazon.com/images/P/9626340762.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/9626340762.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/9626340762.01.LZZZZZZZ.jpg

This line checks which books have been rated at least 40 times by well-read users

In [70]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=40
y

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    False
 Always Have Popsicles                                                                                        False
 Apple Magic (The Collector's series)                                                                         False
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   False
 Clifford Visita El Hospital (Clifford El Gran Perro Colorado)                                                False
                                                                                                              ...
Ã?Â?ber das Fernsehen.                                                                                        False
Ã?Â?ber die Pflicht zum Ungehorsam gegen den Staat.                                                           False
Ã?Â?lpiraten.                                                                                                 False
Ã?Â?stlich der Berge.                                                                                         False
Ã?Â?thique en toc                                                                                             False
Name: Book-Rating, Length: 155845, dtype: bool

In [71]:
famous_books = y[y].index
famous_books

Index(['1984', '1st to Die: A Novel', '2010: Odyssey Two', '204 Rosewood Lane',
       '24 Hours', '2nd Chance', '4 Blondes', '84 Charing Cross Road',
       'A 2nd Helping of Chicken Soup for the Soul (Chicken Soup for the Soul Series (Paper))',
       'A Beautiful Mind: The Life of Mathematical Genius and Nobel Laureate John Nash',
       ...
       'Without Remorse', 'Wizard and Glass (The Dark Tower, Book 4)',
       'Women Who Run with the Wolves',
       'Word Freak: Heartbreak, Triumph, Genius, and Obsession in the World of Competitive Scrabble Players',
       'Wuthering Heights', 'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=1056)

This line filters the ratings to include only those for books that are considered famous (rated at least 40 times by well-read users)

In [72]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

Make a pivot table

In [73]:
pvt = final_ratings.pivot_table(index="Book-Title",columns="User-ID",values='Book-Rating')
pvt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010: Odyssey Two,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204 Rosewood Lane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24 Hours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [75]:
pvt.fillna(0,inplace=True)

Lets computes the cosine similarity between all book vectors based on user ratings from the pivot table.

In [77]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_scores = cosine_similarity(pvt)

In [78]:
similarity_scores.shape

(1056, 1056)

In [88]:
def recommend_book(name):
    """This function takes a book title as input and returns a list of the top 5
    most similar books based on cosine similarity of user ratings."""
    index = np.where(pvt.index==name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:6]

    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title'] == pvt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        data.append(item)

    return data

In [91]:
recommend_book("Women Who Run with the Wolves")

[['Rose', 'V.C. Andrews'],
 ['Contact', 'Susan Grant'],
 ['Dead Run', 'Erica Spindler'],
 ['The World According to Garp', 'John Irving'],
 ['Cold Mountain', 'Charles Frazier']]